# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.31.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin@^6.9.1'
          - eslint@^8.57.0
          - eslint-config-next@^14.2.13
          - eslint-config-prettier@^9.1.0
          - eslint-formatter-table@^7.32.1
          - eslint-plugin-prettier@^5.2.1
          - eslint-plugin-project-structure@^3.13.1
          - eslint-plugin-you-dont-need-lodash-underscore@^6.14.0
          - next@^14.2.13
          - prettier@^3.4.2
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.22.0
    hooks:
      - id: stylelint
        args: [--fix]
        additional_dependencies:
          - '@types/stylelint-webpack-plugin@^2.1.0'
          - stylelint@^15.11.0
          - stylelint-config-rational-order@^0.1.2
          - stylelint-config-recommended-scss@^13.1.0
          - stylelint-config-standard@^34.0.0
          - stylelint-no-unsupported-browser-features@^7.0.0
          - stylelint-order@^6.0.4
          - stylelint-scss@^5.3.0
          - stylelint-webpack-plugin@^4.1.1
  - repo: local
    hooks:
      - id: tsc-files-no-emit
        name: TypeScript Check
        entry: tsc-files --noEmit
        language: node
        files: \.(ts|tsx)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --show-fixes]
        files: ^functions/
      # Run the formatter.
      - id: ruff-format